snakemake_modules: "/mnt/tank/scratch/rskitchenko/projects/snakemake_common_modules/modules/"

GRCh38:
  GATK_b38:
    reference_fasta: "/mnt/archive/shared/references/GRCh38/GATK_b38/Homo_sapiens_assembly38.fasta"
    snps: "/mnt/archive/shared/references/GRCh38/GATK_b38/Homo_sapiens_assembly38.dbsnp138.vcf"
    indels: "/mnt/archive/shared/references/GRCh38/GATK_b38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
    wgs_calling_regions: "/mnt/archive/shared/references/GRCh38/GATK_b38/wgs_calling_regions.hg38.interval_list"
  somatic_hg38:
    af_only_gnomad: "/mnt/archive/shared/references/GRCh38/somatic-hg38/af-only-gnomad.hg38.vcf.gz"
    small_exac_common: "/mnt/archive/shared/references/GRCh38/somatic-hg38/small_exac_common_3.hg38.vcf.gz"

tools:
  samtools: "/usr/bin/samtools"
  picard_old: "/nfs/home/rskitchenko/picard-tools-2.0.1/picard.jar"
  manta:
    configManta: "/mnt/tank/scratch/rskitchenko/anaconda3/envs/py27/bin/configManta.py"
    convertInversion: "/mnt/tank/scratch/rskitchenko/anaconda3/envs/py27/share/manta-1.6.0-1/libexec/convertInversion.py"
  deepvariant: "/mnt/tank/scratch/rskitchenko/projects/low_cow/100_1kg_samples_study/deepvariant_1.2.0.sif"
  glnexus_cli: "/mnt/tank/scratch/rskitchenko/projects/low_cow/100_1kg_samples_study/GLnexus/glnexus_cli"
  vep:
    vep: "/mnt/tank/scratch/rskitchenko/ensembl-vep_latest.sif"
    cache: "/mnt/tank/scratch/rskitchenko/.vep"
    plugins: "/mnt/tank/scratch/rskitchenko/.vep/Plugins"
    plugins_data:
      MPC: "/mnt/tank/scratch/rskitchenko/.vep/Plugins_data/fordist_constraint_official_mpc_values_v2.grch38.txt.gz"

panel_capture:
  target: "/mnt/tank/scratch/rskitchenko/projects/medulo/data/ftp.evrogen.net/21110951/truseq-exome-targeted-regions-manifest-v1-2.GRCh38.bed"
  intervals: "/mnt/tank/scratch/rskitchenko/projects/medulo/data/ftp.evrogen.net/21110951/truseq-exome-targeted-regions-manifest-v1-2.GRCh38.intervals"
  interval_list: "/mnt/tank/scratch/rskitchenko/projects/medulo/data/ftp.evrogen.net/21110951/truseq-exome-targeted-regions-manifest-v1-2.GRCh38.interval_list"
