references:
  genome_fa: "/mnt/archive/shared/references/GRCh38/GATK_b38/Homo_sapiens_assembly38.fasta"
  dict: "/mnt/archive/shared/references/GRCh38/GATK_b38/Homo_sapiens_assembly38.fasta.dict"
  snps: "/mnt/archive/shared/references/GRCh38/GATK_b38/Homo_sapiens_assembly38.dbsnp138.vcf"
  indels: "/mnt/archive/shared/references/GRCh38/GATK_b38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  wgs_calling_regions: "/mnt/archive/shared/references/GRCh38/GATK_b38/wgs_calling_regions.hg38.interval_list"
  af_only_gnomad: "/mnt/archive/shared/references/GRCh38/somatic-hg38/af-only-gnomad.hg38.vcf.gz"
  small_exac_common: "/mnt/archive/shared/references/GRCh38/somatic-hg38/small_exac_common_3.hg38.vcf.gz"