references:
  genome_fa: "....../GATK_b38/Homo_sapiens_assembly38.fasta"
  dict: "....../GATK_b38/Homo_sapiens_assembly38.fasta.dict"
  snps: "....../GATK_b38/Homo_sapiens_assembly38.dbsnp138.vcf"
  indels: "....../GATK_b38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  wgs_calling_regions: "....../GATK_b38/wgs_calling_regions.hg38.interval_list"
  small_exac_common: "....../GRCh38/somatic-hg38/small_exac_common_3.hg38.vcf.gz"
