references:
  genome_fa: "....../GATK_b37/Homo_sapiens_assembly19.fasta"
  dict: "....../GATK_b37/Homo_sapiens_assembly19.dict"
  snps: "....../GATK_b37/Homo_sapiens_assembly19.dbsnp138.vcf"
  indels: "....../GATK_b37/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
  wgs_calling_regions: "....../GATK_b37/wgs_calling_regions.v1.interval_list"
  small_exac_common: "....../GATK_b37/small_exac_common_3.vcf"
