tools:

  singularity: "/usr/local/bin/singularity"
  samtools: "/usr/local/conda/bin/samtools"
  gatk: "/usr/local/conda/bin/gatk"
  bwa_mem2: "/usr/local/conda/bin/bwa-mem2"
  picard_old: "/usr/ngs/picard-tools-2.0.1/picard.jar"
  bcftools: "/usr/local/conda/bin/bcftools"

  vep:
    path: "/usr/ngs/ensembl-vep.sif"
    cache: "......./vep_data"
    plugins: "......./VEP_plugins"
    plugins_data:
      MPC: "......./fordist_constraint_official_mpc_values_v2.txt.gz"
      ExACpLI: "......./fordist_cleaned_exac_r03_march16_z_pli_rec_null_data.txt"
      gnomAD_pLI: "......./gnomad.v2.1.1.lof_metrics.by_gene.gene_pli.txt"
