references:
  genome_fa: "/mnt/archive/shared/references/GRCh37/GATK_b37/Homo_sapiens_assembly19.fasta"
  dict: "/mnt/archive/shared/references/GRCh37/GATK_b37/Homo_sapiens_assembly19.dict"
  snps: "/mnt/archive/shared/references/GRCh37/GATK_b37/Homo_sapiens_assembly19.dbsnp138.vcf"
  indels: "/mnt/archive/shared/references/GRCh37/GATK_b37/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
  wgs_calling_regions: "/mnt/archive/shared/references/GRCh37/GATK_b37/wgs_calling_regions.v1.interval_list"
  af_only_gnomad: "/mnt/archive/shared/references/GRCh37/GATK_b37/af-only-gnomad.raw.sites.vcf"
  small_exac_common: "/mnt/archive/shared/references/GRCh37/GATK_b37/small_exac_common_3.vcf"
