grm_dir: 'data/grm'
tmr_dir: 'data/tmr'

snakemake_modules: "modules/"

tools:
  samtools: "/opt/conda/envs/smk/bin/samtools"
  bwa_mem2: "/ngs_pipeline/tools/bwa-mem2/bwa-mem2"
  gatk: "/opt/conda/envs/smk/bin/gatk"
  singularity: "/usr/local/bin/singularity"
  picard_old: "/ngs_pipeline/tools/picard-tools-2.0.1/picard.jar"
  bcftools: "/opt/conda/envs/smk/bin/bcftools"
  deepvariant: "/ngs_pipeline/tools/deepvariant_latest.sif"
  vep: 
    path: "/ngs_pipeline/tools/ensembl-vep_latest.sif"
    cache: "/ngs_pipeline/app/ngs_refs/vep_cache"
    plugins: "/ngs_pipeline/app/ngs_refs/VEP_plugins"

