grm_dir: 'data/grm'
tmr_dir: 'data/tmr'

panel_capture:
  target: 'data/capture.bed'

snakemake_modules: "modules/"

references37:
  genome_fa: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/Homo_sapiens_assembly19.fasta"
  dict: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/Homo_sapiens_assembly19.dict"
  snps: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/Homo_sapiens_assembly19.dbsnp138.vcf"
  indels: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
  wgs_calling_regions: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/wgs_calling_regions.v1.interval_list"
  af_only_gnomad: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/af-only-gnomad.raw.sites.vcf"
  small_exac_common: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/small_exac_common_3.vcf"

references38:
  genome_fa: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/GATK_b38/Homo_sapiens_assembly38.fasta"
  dict: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/GATK_b38/Homo_sapiens_assembly38.fasta.dict"
  snps: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/GATK_b38/Homo_sapiens_assembly38.dbsnp138.vcf"
  indels: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/GATK_b38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  wgs_calling_regions: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/GATK_b38/wgs_calling_regions.hg38.interval_list"
  af_only_gnomad: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/somatic-hg38/af-only-gnomad.hg38.vcf.gz"
  small_exac_common: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/somatic-hg38/small_exac_common_3.hg38.vcf.gz"

tools:
  samtools: "/ngs_pipeline/tools/samtools-1.9/samtools"
  bwa_mem2: "/ngs_pipeline/tools/bwa-mem2/bwa-mem2"
  gatk: "/opt/conda/envs/smk/bin/gatk"
  singularity: "/opt/conda/envs/smk/bin/singularity"
  picard_old: "/ngs_pipeline/tools/picard-tools-2.0.1/picard.jar"
  bcftools: "/ngs_pipeline/tools/bcftools-1.9/bcftools"
  vep: 
    path: "/ngs_pipeline/tools/ensembl-vep_latest.sif"
    cache: "/ngs_pipeline/app/ngs_refs/vep_cache"
    plugins: "/ngs_pipeline/app/ngs_refs/VEP_plugins"
    plugins_data:
      MPC: "/ngs_pipeline/app/ngs_refs/VEP_plugins/fordist_constraint_official_mpc_values_v2.txt.gz"
