references:
  genome_fa: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/Homo_sapiens_assembly38.fasta"
  dict: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/Homo_sapiens_assembly38.dict"
  snps: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/Homo_sapiens_assembly38.dbsnp138.vcf"
  indels: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  wgs_calling_regions: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/wgs_calling_regions.hg38.interval_list"
  vqsr:
    hapmap:       "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/hapmap_3.3.hg38.vcf.gz"
    omni:         "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/1000G_omni2.5.hg38.vcf.gz"
    thousandg_snps: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
    mills:        "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
    axiom_poly:   "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz"
  af_only_gnomad: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/somatic-hg38/af-only-gnomad.hg38.vcf.gz"
  small_exac_common: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/somatic-hg38/small_exac_common_3.hg38.vcf.gz"
  wes_joint_gvcfs: '/ngs_pipeline/app/ngs_refs/GRCh38_boundle/wes_joint_gvcfs/'
  pon: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/somatic-hg38/1000g_pon.hg38.vcf.gz"
  wes_gene_panels:
    - name: ccp
      bed: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/captures/ccp.bed"
    - name: chol
      bed: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/captures/chol.bed"
    - name: cilia
      bed: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/captures/cilia.bed"
    - name: endo
      bed: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/captures/endo.bed"
    - name: hcmp
      bed: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/captures/hcmp.bed"
    - name: hematopoiesis
      bed: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/captures/hematopoiesis.bed"
    - name: lqts
      bed: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/captures/lqts.bed"
    - name: rare
      bed: "/ngs_pipeline/app/ngs_refs/GRCh38_boundle/captures/rare.bed"
  vep_plugins_data:
      CADD: "/ngs_pipeline/app/ngs_refs/VEP_plugins/whole_genome_SNVs.hg38.tsv.gz"
      AlphaMissense: "/ngs_pipeline/app/ngs_refs/VEP_plugins/AlphaMissense_hg38.tsv.gz"
      ExACpLI: "/ngs_pipeline/app/ngs_refs/VEP_plugins/plI_gene.txt"
      Phenotypes: "/ngs_pipeline/app/ngs_refs/VEP_plugins/Phenotypes.pm_homo_sapiens_114_GRCh38.gvf.gz"
      REVEL: "/ngs_pipeline/app/ngs_refs/VEP_plugins/revel_scores.hg38.tsv.gz"
      MPC: "/ngs_pipeline/app/ngs_refs/VEP_plugins/fordist_constraint_official_mpc_values_v2.hg38.fixed.txt.gz"
      SpliceAI_SNV: "/ngs_pipeline/app/ngs_refs/VEP_plugins/spliceai/spliceai_scores.masked.snv.ensembl_mane_v1.4.grch38.vcf.gz"
      SpliceAI_INDEL: "/ngs_pipeline/app/ngs_refs/VEP_plugins/spliceai/spliceai_scores.masked.snv.ensembl_mane_v1.4.grch38.vcf.gz"
      custom:
          ClinVar: "/ngs_pipeline/app/ngs_refs/VEP_plugins/custom_anno/clinvar.vcf.gz"
          mart: "/ngs_pipeline/app/ngs_refs/VEP_plugins/custom_anno/mart_export.tsv"
          SNPred: "/ngs_pipeline/app/ngs_refs/VEP_plugins/custom_anno/SNPred_scores.vcf.gz"
          rank: "/ngs_pipeline/app/ngs_refs/VEP_plugins/custom_anno/gse71613_ranking.tsv"
          # Orphanet: '/ngs_pipeline/app/ngs_refs/VEP_plugins/custom_anno/orphadata.bed.gz'