grm_dir: 'data/grm'
tmr_dir: 'data/tmr'

panel_capture:
  target: "data/capture.bed"

run: 'wes_mb5'
ngs_type: 'WES'
hs: true
reads_type: 'pair'

assembly: 'GRCh37'

snakemake_modules: "modules/"

references37:
  genome_fa: "/mnt/StudentsWork/skitchenko/ngs_refs/GRCh37_boundle/Homo_sapiens_assembly19.fasta"
  dict: "/mnt/StudentsWork/skitchenko/ngs_refs/GRCh37_boundle/Homo_sapiens_assembly19.dict"
  snps: "/mnt/StudentsWork/skitchenko/ngs_refs/GRCh37_boundle/Homo_sapiens_assembly19.dbsnp138.vcf"
  indels: "/mnt/StudentsWork/skitchenko/ngs_refs/GRCh37_boundle/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
  wgs_calling_regions: "/mnt/StudentsWork/skitchenko/ngs_refs/GRCh37_boundle/wgs_calling_regions.v1.interval_list"
  af_only_gnomad: "/mnt/StudentsWork/skitchenko/ngs_refs/GRCh37_boundle/af-only-gnomad.raw.sites.vcf"
  small_exac_common: "/mnt/StudentsWork/skitchenko/ngs_refs/GRCh37_boundle/small_exac_common_3.vcf"

references38:
  genome_fa: "/mnt/archive/shared/references/GRCh38/GATK_b38/Homo_sapiens_assembly38.fasta"
  dict: "/mnt/archive/shared/references/GRCh38/GATK_b38/Homo_sapiens_assembly38.fasta.dict"
  snps: "/mnt/archive/shared/references/GRCh38/GATK_b38/Homo_sapiens_assembly38.dbsnp138.vcf"
  indels: "/mnt/archive/shared/references/GRCh38/GATK_b38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  wgs_calling_regions: "/mnt/archive/shared/references/GRCh38/GATK_b38/wgs_calling_regions.hg38.interval_list"
  af_only_gnomad: "/mnt/archive/shared/references/GRCh38/somatic-hg38/af-only-gnomad.hg38.vcf.gz"
  small_exac_common: "/mnt/archive/shared/references/GRCh38/somatic-hg38/small_exac_common_3.hg38.vcf.gz"

tools:
  samtools: "/usr/bin/samtools" 
  bwa_mem2: "/mnt/tank/scratch/rskitchenko/anaconda3/bin/bwa-mem2"
  gatk: "/mnt/tank/scratch/rskitchenko/anaconda3/envs/smk/bin/gatk"
  singularity: "/usr/local/bin/singularity"
  picard_old: "/nfs/home/rskitchenko/picard-tools-2.0.1/picard.jar"
  bcftools: "/nfs/home/rskitchenko/tools/bcftools-1.11/bcftools"
  vep: 
    path: "/mnt/tank/scratch/rskitchenko/ensembl-vep_latest.sif"
    cache: "/mnt/tank/scratch/rskitchenko/.vep"
    plugins: "/mnt/tank/scratch/rskitchenko/.vep/VEP_plugins"
    plugins_data:
      MPC: "/mnt/tank/scratch/rskitchenko/.vep/Plugins_data/fordist_constraint_official_mpc_values_v2.txt.gz"
