references:
  genome_fa: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/Homo_sapiens_assembly19.fasta"
  dict: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/Homo_sapiens_assembly19.dict"
  snps: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/Homo_sapiens_assembly19.dbsnp138.vcf"
  indels: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
  wgs_calling_regions: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/wgs_calling_regions.v1.interval_list"
  af_only_gnomad: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/af-only-gnomad.raw.sites.vcf"
  small_exac_common: "/ngs_pipeline/app/ngs_refs/GRCh37_boundle/small_exac_common_3.vcf"
  vep_plugins_data:
      MPC: "/ngs_pipeline/app/ngs_refs/VEP_plugins/fordist_constraint_official_mpc_values_v2.txt.gz"
      CADD: "/ngs_pipeline/app/ngs_refs/VEP_plugins/whole_genome_SNVs.hg37.tsv.gz"
      AlphaMissense: "/ngs_pipeline/app/ngs_refs/VEP_plugins/AlphaMissense_hg37.tsv.gz"
